remote_theme: pages-themes/architect@v0.2.0
title: Miracle Ostrich
description: Python, Notebooks, and sometimes... Ostrich Miracles.
header_logo: "/assets/img/cute-ostrich.png"

header_pages:
  - index.html
  - about.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  docs:
    output: true
    permalink: /docs/:name/
